---
name: release
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job001:
    name: Build pmix
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
      options: --privileged
    steps:
      - name: Install dnf-plugins-core - this used to be done in base image
        run: |
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled powertools
          dnf install -y rpm-build automake autoconf libtool make pkg-config less vim flex bison doxygen cmake bash-doc which
          dnf upgrade -y
      
