---
name: release
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job001:
    name: Build pmix
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
      options: --privileged
    steps:
      - name: Prepare base build env
        run: |
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled powertools
          dnf install -y rpm-build automake autoconf libtool make pkg-config less vim flex bison doxygen cmake bash-doc which wget
          dnf upgrade -y
          mkdir -p $HOME/rpmbuild/SOURCES/
      - name: Install pmix-specific pkgs
        run: |
          dnf install -y zlib-devel hwloc-devel libevent-devel python3-devel jansson-devel
          python3 -m pip install sphinx
      - name: Download pmix and unpack it
        run: |
          export PMIX_VERSION="4.2.7"
          export PMIX_RELEASE="$(date +%Y%m%d%H%M%S)%{?dist}"
          wget https://github.com/openpmix/openpmix/releases/download/v${PMIX_VERSION}/pmix-${PMIX_VERSION}.tar.bz2
          tar -xvf ./pmix*
          cp pmix-*.tar.bz2 $HOME/rpmbuild/SOURCES/
          sed -i "s/^Release.*$/Release: ${PMIX_RELEASE}%{?dist}/g" pmix-*/contrib/pmix.spec
          cat pmix-*/contrib/pmix.spec
          pwd
          whoami
          
      
