---
name: release
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  DOCKER_REPO_BASE: josed/build_slurm_base
  DOCKER_REPO_PMIX: josed/build_slurm_pmix
  DOCKER_REPO_SLURM: josed/build_slurm_slurm
  APPTAINER_URL: https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
  APPTAINER_DEB: apptainer_1.2.4_amd64.deb
  PMIX_VERSION: 4.2.7
  SLURM_VERSION: 23.02.6
  
jobs:
  build_base_image:
    name: Build base apptainer image
    runs-on: ubuntu-latest
    steps:
      - name: Install apptainer
        run: |
          sudo apt update
          sudo apt install -y wget dnf
          cd /tmp
          wget --quiet ${APPTAINER_URL}
          sudo apt install -y ./${APPTAINER_DEB}

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            base-rpmbuild-rocky8.def
          sparse-checkout-cone-mode: false

      - name: build base image in apptainer
        run: |
          sudo echo '%_var /var' > /root/.rpmmacros
          sudo echo '%_dbpath %{_var}/lib/rpm' >> /root/.rpmmacros
          sudo apptainer build ./base-rpmbuild-rocky8.sif ./base-rpmbuild-rocky8.def
  
  build_pmix_build_image:
    name: Build pmix apptainer image
    runs-on: ubuntu-latest
    needs: build_base_image
    outputs:
      image: ${{ env.DOCKER_REPO_BASE }}
    steps:
      - name: Install apptainer
        run: |
          sudo apt update
          sudo apt install -y wget dnf
          cd /tmp
          wget --quiet ${APPTAINER_URL}
          sudo apt install -y ./${APPTAINER_DEB}


    
    
