---

# almost working docker version here: https://gist.github.com/jose-d/c69ea72ee8eea1d54fddb60da52c7bc1

name: release
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  DOCKER_REPO_BASE: josed/build_slurm_base
  DOCKER_REPO_PMIX: josed/build_slurm_pmix
  DOCKER_REPO_SLURM: josed/build_slurm_slurm
  APPTAINER_URL: https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
  APPTAINER_DEB: apptainer_1.2.4_amd64.deb
  PMIX_VERSION: 4.2.7
  SLURM_VERSION: 23.02.6
  
jobs:
  job000_docker_base:
    name: Build base docker image
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:.github/dockerfiles/base"
          push: false
          tags: ${{ env.DOCKER_REPO_BASE }}

      - name: Login to github registry and push image there
        run: |
          echo ${{ secrets.PACKAGES_SECRET }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo $?
