---
name: release
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  DOCKER_REPO_BASE: josed/build_slurm_base
  DOCKER_REPO_PMIX: josed/build_slurm_pmix
  DOCKER_REPO_SLURM: josed/build_slurm_slurm
  PMIX_VERSION: 4.2.7
  SLURM_VERSION: 23.02.6
  
jobs:
  job000_apptainer_base:
    name: Build base apptainer image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ env.DOCKER_REPO_BASE }}
    steps:
      - name: Install apptainer
        run: |
          sudo apt update
          sudo apt install -y wget
          cd /tmp
          wget --quiet https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
          sudo apt install -y ./apptainer_1.2.4_amd64.deb

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            base-rpmbuild-rocky8.def
          sparse-checkout-cone-mode: false

    
    
