---

name: Build Slurm Debug
run-name: ${{ github.actor }} is attempting to build pmix and slurm 🚀
on: workflow_dispatch
env:
  # github image repository url - used to cache docker images
  IMG_REPO_URL: ghcr.io/jose-d/build-slurm-rocky8
  # version of openpmix and slurm to download and build together
  PMIX_VERSION: 4.2.7
  SLURM_VERSION: 23.02.6
  
jobs:
  build_pmix:
    name: Build pmix
    runs-on: ubuntu-latest
    env:
      GHCR_U: ${{ github.actor }}
      GHCR_S: ${{ secrets.PACKAGES_SECRET }}
    steps:

      - name: checkout pmix build script
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/scripts/build_pmix.sh
          sparse-checkout-cone-mode: false
          path: 'script'
          
      - name: Login to ghcr registry with docker
        run: |
          sudo apt -y install tree
          tree .
          tree .github/
          source ${PERSISTENCE_FILE_PMIX}
          echo $GHCR_S | docker login ghcr.io -u ${GHCR_U} --password-stdin
          docker run --cidfile /tmp/docker_test.cid --env-file $PERSISTENCE_FILE_PMIX -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} -v ${HOME}:${HOME} -w ${GITHUB_WORKSPACE} ${PMIXIMAGE_URL} /bin/bash script/build_pmix.sh
