---
name: release
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job001:
    name: Build pmix
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
      options: --privileged
    steps:
      - name: Prepare base build env
        run: |
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled powertools
          dnf install -y rpm-build automake autoconf libtool make pkg-config less vim flex bison doxygen cmake bash-doc which
          dnf upgrade -y
      - name: Install pmix-specific pkgs
        run: |
          dnf install -y zlib-devel hwloc-devel libevent-devel python3-devel jansson-devel
          python3 -m pip install sphinx
          
      
