---

name: Test slurm docker image build
run-name: ${{ github.actor }} is attempting to build slurm docker image 🚀
on: workflow_dispatch
permissions: write-all
env:
  # github image repository url - used to cache docker images
  IMG_REPO_URL: ghcr.io/jose-d/build-slurm-rocky8
  # version of openpmix and slurm to download and build together
  PMIX_VERSION: 5.0.5
  SLURM_VERSION: 24.11.0
  # version of CUDA to take NVML library from:
  NVML_VERSION: 12-6
  # files used as cache for variables sharing
  GLOBAL_VARS_FILE: global_vars.txt
jobs:

  prolog:
    name: Create global release tag, and related job-specific naming constants and save it into GLOBAL_VARS_FILE
    runs-on: ubuntu-latest
    steps:
      - name: Create vars, save them into GLOBAL_VARS_FILE and GITHUB_STEP_SUMMARY
        shell: bash
        run: |
          # this is the date-based identifier for this release:
          RELTAG="$(date +%Y%m%d%H%M%S)"

          BASEIMAGE_RELTAG="baseimg_${RELTAG}"
          BASEIMAGE_URL="${IMG_REPO_URL}:${BASEIMAGE_RELTAG}"

          SLURMIMAGE_RELTAG="slurmimg_${RELTAG}"
          SLURMIMAGE_URL="${IMG_REPO_URL}:${SLURMIMAGE_RELTAG}"

          PMIXIMAGE_RELTAG="pmiximg_${RELTAG}"
          PMIXIMAGE_URL="${IMG_REPO_URL}:${PMIXIMAGE_RELTAG}"

          touch $GLOBAL_VARS_FILE

          echo "RELTAG=${RELTAG}" | tee --append $GLOBAL_VARS_FILE $GITHUB_STEP_SUMMARY

          echo "BASEIMAGE_RELTAG=${BASEIMAGE_RELTAG}" | tee --append $GLOBAL_VARS_FILE $GITHUB_STEP_SUMMARY
          echo "BASEIMAGE_URL=${BASEIMAGE_URL}" | tee --append $GLOBAL_VARS_FILE $GITHUB_STEP_SUMMARY

          echo "PMIXIMAGE_RELTAG=${PMIXIMAGE_RELTAG}" | tee --append $GLOBAL_VARS_FILE $GITHUB_STEP_SUMMARY
          echo "PMIXIMAGE_URL=${PMIXIMAGE_URL}" | tee --append $GLOBAL_VARS_FILE $GITHUB_STEP_SUMMARY

          echo "SLURMIMAGE_RELTAG=${SLURMIMAGE_RELTAG}" | tee --append $GLOBAL_VARS_FILE $GITHUB_STEP_SUMMARY
          echo "SLURMIMAGE_URL=${SLURMIMAGE_URL}" | tee --append $GLOBAL_VARS_FILE $GITHUB_STEP_SUMMARY


      - name: Upload GLOBAL_VARS_FILE to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GLOBAL_VARS_FILE }}
          path: ${{ env.GLOBAL_VARS_FILE }}

  build_base_build-image:
    name: Build base docker image
    runs-on: ubuntu-latest
    needs:
      - prolog
    steps:

      - name: Download GLOBAL_VARS_FILE
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GLOBAL_VARS_FILE }}

      - name: Import required vars from GLOBAL_VARS_FILE into local env
        shell: bash
        run: |
          source ${GLOBAL_VARS_FILE}
          echo "BASEIMAGE_URL=${BASEIMAGE_URL}" | tee --append ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
          
      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: "{{defaultContext}}:.github/dockerfiles/base"
          push: true
          tags: ${{ env.BASEIMAGE_URL }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
        
  build_slurm_build_image:
    name: Build slurm build docker image
    runs-on: ubuntu-latest
    needs: build_base_build-image
    steps:

      - name: Download GLOBAL_VARS_FILE
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GLOBAL_VARS_FILE }}

      - name: Import required vars from GLOBAL_VARS_FILE into local env
        shell: bash
        run: |
          source ${GLOBAL_VARS_FILE}
          echo "BASEIMAGE_URL=${BASEIMAGE_URL}" | tee --append ${GITHUB_ENV}
          echo "SLURMIMAGE_URL=${SLURMIMAGE_URL}" | tee --append ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          build-args: |
            NVML_VERSION=${{ env.NVML_VERSION }}
            BASE_IMAGE=${{ env.BASEIMAGE_URL }}
          context: "{{defaultContext}}:.github/dockerfiles/slurm"
          push: true
          tags: ${{ env.SLURMIMAGE_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
